# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from widgets.QtWaitingSpinner import QtWaitingSpinner


class Ui_main(object):
    def setupUi(self, main):
        main.setObjectName("main")
        main.setWindowModality(QtCore.Qt.ApplicationModal)
        main.setWindowFlag(QtCore.Qt.FramelessWindowHint)
        main.setEnabled(True)
        main.resize(501, 694)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        main.setFont(font)
        main.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.stackPanel = QtWidgets.QStackedWidget(main)
        self.stackPanel.setGeometry(QtCore.QRect(0, 29, 500, 671))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.stackPanel.setFont(font)
        self.stackPanel.setStyleSheet("border:none\n"
                                      "")
        self.stackPanel.setObjectName("stackPanel")
        self.LoginPage = QtWidgets.QWidget()
        self.LoginPage.setObjectName("LoginPage")
        self.txtEmail_login = QtWidgets.QLineEdit(self.LoginPage)
        self.txtEmail_login.setGeometry(QtCore.QRect(81, 305, 311, 41))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(10)
        self.txtEmail_login.setFont(font)
        self.txtEmail_login.setStyleSheet("border-style: outset;\n"
                                          "border-width: 1px;\n"
                                          "background-color: rgb(231, 231, 231);\n"
                                          "border-radius: 8px;\n"
                                          "border-color: rgb(194,194,194);\n"
                                          "padding: 4px;")
        self.txtEmail_login.setText("")
        self.txtEmail_login.setObjectName("txtEmail_login")
        self.label_3 = QtWidgets.QLabel(self.LoginPage)
        self.label_3.setGeometry(QtCore.QRect(110, 55, 251, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(27)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:rgb(63, 61, 84)")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.btnFacebook = QtWidgets.QPushButton(self.LoginPage)
        self.btnFacebook.setGeometry(QtCore.QRect(154, 145, 55, 50))
        self.btnFacebook.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnFacebook.setAutoFillBackground(False)
        self.btnFacebook.setStyleSheet("QPushButton{\n"
                                       "color: #333;\n"
                                       "border: 0px solid  rgb(231, 231, 231);\n"
                                       "background-color: rgb(231, 231, 231);\n"
                                       "border-radius: 12px;\n"
                                       "color:rgb(240, 240, 240)\n"
                                       "}\n"
                                       "QPushButton:pressed{\n"
                                       "background-color: rgb(240, 240, 240);\n"
                                       "border-color: rgb(240, 240, 240);\n"
                                       "}")
        self.btnFacebook.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Icons/icons8-facebook-circled-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnFacebook.setIcon(icon)
        self.btnFacebook.setIconSize(QtCore.QSize(32, 32))
        self.btnFacebook.setFlat(False)
        self.btnFacebook.setObjectName("btnFacebook")
        self.chkRememberme = QtWidgets.QCheckBox(self.LoginPage)
        self.chkRememberme.setGeometry(QtCore.QRect(90, 445, 111, 19))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.chkRememberme.setFont(font)
        self.chkRememberme.setStyleSheet("color: rgb(124, 122, 133);")
        self.chkRememberme.setObjectName("chkRememberme")
        self.label_4 = QtWidgets.QLabel(self.LoginPage)
        self.label_4.setGeometry(QtCore.QRect(180, 215, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(194, 194, 194);\n"
                                   "padding-bottom: 4px;\n"
                                   "font-weight: 600;")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.txtPassword_login = QtWidgets.QLineEdit(self.LoginPage)
        self.txtPassword_login.setGeometry(QtCore.QRect(81, 395, 311, 41))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(10)
        self.txtPassword_login.setFont(font)
        self.txtPassword_login.setStyleSheet("border-style: outset;\n"
                                             "border-width: 1px;\n"
                                             "background-color: rgb(231, 231, 231);\n"
                                             "border-radius: 8px;\n"
                                             "border-color: rgb(194,194,194);\n"
                                             "padding: 4px;")
        self.txtPassword_login.setText("")
        self.txtPassword_login.setObjectName("txtPassword_login")
        self.btnForgotpwd = QtWidgets.QPushButton(self.LoginPage)
        self.btnForgotpwd.setGeometry(QtCore.QRect(248, 440, 140, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnForgotpwd.setFont(font)
        self.btnForgotpwd.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnForgotpwd.setStyleSheet("QPushButton{\n"
                                        "color: rgb(63, 61, 84);\n"
                                        "border: 0px;\n"
                                        "background-color: rgb(255, 255, 255);\n"
                                        "}\n"
                                        "QPushButton:pressed{\n"
                                        "    color: rgb(103, 100, 138);\n"
                                        "}")
        self.btnForgotpwd.setObjectName("btnForgotpwd")
        self.lblEmail_2 = QtWidgets.QLabel(self.LoginPage)
        self.lblEmail_2.setGeometry(QtCore.QRect(81, 277, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblEmail_2.setFont(font)
        self.lblEmail_2.setStyleSheet("color: rgb(63, 61, 85);")
        self.lblEmail_2.setObjectName("lblEmail_2")
        self.lblPassword_2 = QtWidgets.QLabel(self.LoginPage)
        self.lblPassword_2.setGeometry(QtCore.QRect(81, 355, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblPassword_2.setFont(font)
        self.lblPassword_2.setStyleSheet("color: rgb(63, 61, 85);")
        self.lblPassword_2.setObjectName("lblPassword_2")
        self.btnLogin = QtWidgets.QPushButton(self.LoginPage)
        self.btnLogin.setGeometry(QtCore.QRect(80, 485, 311, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnLogin.setFont(font)
        self.btnLogin.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnLogin.setAutoFillBackground(False)
        self.btnLogin.setStyleSheet("QPushButton{\n"
                                    "color: rgb(255, 255, 255);\n"
                                    "background-color: rgb(63, 61, 84);\n"
                                    "border: 2px solid  rgb(63, 61, 94);\n"
                                    "border-radius: 8px;\n"
                                    "padding: 4px;\n"
                                    "box-shadow: 0 2px 2px 0 rgba(0, 0, 0, 0.16), 0 0 0 1px rgba(0, 0, 0, 0.08);\n"
                                    "}\n"
                                    "QPushButton:pressed{\n"
                                    "    background-color: rgb(103, 100, 138);\n"
                                    "}")
        self.btnLogin.setAutoDefault(False)
        self.btnLogin.setDefault(False)
        self.btnLogin.setFlat(True)
        self.btnLogin.setObjectName("btnLogin")
        self.btnGoogle = QtWidgets.QPushButton(self.LoginPage)
        self.btnGoogle.setGeometry(QtCore.QRect(254, 145, 55, 50))
        self.btnGoogle.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnGoogle.setAutoFillBackground(False)
        self.btnGoogle.setStyleSheet("QPushButton{\n"
                                     "color: #333;\n"
                                     "border: 0px solid  rgb(231, 231, 231);\n"
                                     "background-color: rgb(231, 231, 231);\n"
                                     "border-radius: 12px;\n"
                                     "color:rgb(240, 240, 240)\n"
                                     "}\n"
                                     "QPushButton:pressed{\n"
                                     "background-color: rgb(240, 240, 240);\n"
                                     "border-color: rgb(240, 240, 240);\n"
                                     "}")
        self.btnGoogle.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Icons/icons8-google-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnGoogle.setIcon(icon1)
        self.btnGoogle.setIconSize(QtCore.QSize(32, 32))
        self.btnGoogle.setObjectName("btnGoogle")
        self.label_10 = QtWidgets.QLabel(self.LoginPage)
        self.label_10.setGeometry(QtCore.QRect(100, 535, 190, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(124, 122, 133);")
        self.label_10.setObjectName("label_10")
        self.btnSignupPage = QtWidgets.QPushButton(self.LoginPage)
        self.btnSignupPage.setGeometry(QtCore.QRect(290, 535, 60, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnSignupPage.setFont(font)
        self.btnSignupPage.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSignupPage.setStyleSheet("QPushButton{\n"
                                         "color: rgb(63, 61, 84);\n"
                                         "border: 0px;\n"
                                         "background-color: rgb(255, 255, 255);\n"
                                         "}\n"
                                         "QPushButton:pressed{\n"
                                         "    color: rgb(103, 100, 138);\n"
                                         "}")
        self.btnSignupPage.setCheckable(False)
        self.btnSignupPage.setAutoExclusive(False)
        self.btnSignupPage.setDefault(False)
        self.btnSignupPage.setObjectName("btnSignupPage")
        self.frame_3 = QtWidgets.QFrame(self.LoginPage)
        self.frame_3.setGeometry(QtCore.QRect(50, 220, 120, 2))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 2))
        self.frame_3.setMaximumSize(QtCore.QSize(200, 2))
        self.frame_3.setStyleSheet("background-color: rgb(231, 231, 231);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.frame_6 = QtWidgets.QFrame(self.LoginPage)
        self.frame_6.setGeometry(QtCore.QRect(301, 220, 120, 2))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setMinimumSize(QtCore.QSize(0, 2))
        self.frame_6.setMaximumSize(QtCore.QSize(200, 2))
        self.frame_6.setStyleSheet("background-color: rgb(231, 231, 231);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.lblError_login = QtWidgets.QLabel(self.LoginPage)
        self.lblError_login.setGeometry(QtCore.QRect(80, 245, 310, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblError_login.setFont(font)
        self.lblError_login.setStyleSheet("QLabel{\n"
                                          "color: rgb(250,0,0);\n"
                                          "line-spacing: 2px;\n"
                                          "}")
        self.lblError_login.setText("")
        self.lblError_login.setObjectName("lblError_login")
        self.stackPanel.addWidget(self.LoginPage)
        self.SignupPage = QtWidgets.QWidget()
        self.SignupPage.setObjectName("SignupPage")
        self.label_2 = QtWidgets.QLabel(self.SignupPage)
        self.label_2.setGeometry(QtCore.QRect(180, 180, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(194, 194, 194);\n"
                                   "padding-bottom: 4px;\n"
                                   "font-weight: 600;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.txtEmail_signup = QtWidgets.QLineEdit(self.SignupPage)
        self.txtEmail_signup.setGeometry(QtCore.QRect(81, 270, 311, 41))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(10)
        self.txtEmail_signup.setFont(font)
        self.txtEmail_signup.setStyleSheet("border-style: outset;\n"
                                           "border-width: 1px;\n"
                                           "background-color: rgb(231, 231, 231);\n"
                                           "border-radius: 8px;\n"
                                           "border-color: rgb(194,194,194);\n"
                                           "padding: 4px;")
        self.txtEmail_signup.setText("")
        self.txtEmail_signup.setObjectName("txtEmail_signup")
        self.btnFacebookSignup = QtWidgets.QPushButton(self.SignupPage)
        self.btnFacebookSignup.setGeometry(QtCore.QRect(154, 110, 55, 50))
        self.btnFacebookSignup.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnFacebookSignup.setAutoFillBackground(False)
        self.btnFacebookSignup.setStyleSheet("QPushButton{\n"
                                             "color: #333;\n"
                                             "border: 0px solid  rgb(231, 231, 231);\n"
                                             "background-color: rgb(231, 231, 231);\n"
                                             "border-radius: 12px;\n"
                                             "color:rgb(240, 240, 240)\n"
                                             "}\n"
                                             "QPushButton:pressed{\n"
                                             "background-color: rgb(240, 240, 240);\n"
                                             "border-color: rgb(240, 240, 240);\n"
                                             "}")
        self.btnFacebookSignup.setText("")
        self.btnFacebookSignup.setIcon(icon)
        self.btnFacebookSignup.setIconSize(QtCore.QSize(32, 32))
        self.btnFacebookSignup.setObjectName("btnFacebookSignup")
        self.label = QtWidgets.QLabel(self.SignupPage)
        self.label.setGeometry(QtCore.QRect(110, 20, 251, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(27)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgb(63, 61, 84)")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.txtPassword_signup = QtWidgets.QLineEdit(self.SignupPage)
        self.txtPassword_signup.setGeometry(QtCore.QRect(81, 360, 311, 41))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(10)
        self.txtPassword_signup.setFont(font)
        self.txtPassword_signup.setStyleSheet("border-style: outset;\n"
                                              "border-width: 1px;\n"
                                              "background-color: rgb(231, 231, 231);\n"
                                              "border-radius: 8px;\n"
                                              "border-color: rgb(194,194,194);\n"
                                              "padding: 4px;")
        self.txtPassword_signup.setText("")
        self.txtPassword_signup.setObjectName("txtPassword_signup")
        self.lblEmail = QtWidgets.QLabel(self.SignupPage)
        self.lblEmail.setGeometry(QtCore.QRect(81, 242, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblEmail.setFont(font)
        self.lblEmail.setStyleSheet("color: rgb(63, 61, 85);")
        self.lblEmail.setObjectName("lblEmail")
        self.lblPassword = QtWidgets.QLabel(self.SignupPage)
        self.lblPassword.setGeometry(QtCore.QRect(81, 320, 100, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblPassword.setFont(font)
        self.lblPassword.setStyleSheet("color: rgb(63, 61, 85);")
        self.lblPassword.setObjectName("lblPassword")
        self.btnSignup = QtWidgets.QPushButton(self.SignupPage)
        self.btnSignup.setGeometry(QtCore.QRect(80, 515, 311, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnSignup.setFont(font)
        self.btnSignup.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSignup.setStyleSheet("QPushButton{\n"
                                     "color: rgb(255, 255, 255);\n"
                                     "background-color: rgb(63, 61, 84);\n"
                                     "border: 2px solid  rgb(63, 61, 94);\n"
                                     "border-radius: 8px;\n"
                                     "padding: 4px;\n"
                                     "box-shadow: 0 2px 2px 0 rgba(0, 0, 0, 0.16), 0 0 0 1px rgba(0, 0, 0, 0.08);\n"
                                     "}\n"
                                     "QPushButton:pressed{\n"
                                     "    background-color: rgb(103, 100, 138);\n"
                                     "}")
        self.btnSignup.setObjectName("btnSignup")
        self.btnGoogleSignup = QtWidgets.QPushButton(self.SignupPage)
        self.btnGoogleSignup.setGeometry(QtCore.QRect(254, 110, 55, 50))
        self.btnGoogleSignup.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnGoogleSignup.setAutoFillBackground(False)
        self.btnGoogleSignup.setStyleSheet("QPushButton{\n"
                                           "color: #333;\n"
                                           "border: 0px solid  rgb(231, 231, 231);\n"
                                           "background-color: rgb(231, 231, 231);\n"
                                           "border-radius: 12px;\n"
                                           "color:rgb(240, 240, 240)\n"
                                           "}\n"
                                           "QPushButton:pressed{\n"
                                           "background-color: rgb(240, 240, 240);\n"
                                           "border-color: rgb(240, 240, 240);\n"
                                           "}")
        self.btnGoogleSignup.setText("")
        self.btnGoogleSignup.setIcon(icon1)
        self.btnGoogleSignup.setIconSize(QtCore.QSize(32, 32))
        self.btnGoogleSignup.setObjectName("btnGoogleSignup")
        self.label_9 = QtWidgets.QLabel(self.SignupPage)
        self.label_9.setGeometry(QtCore.QRect(96, 565, 200, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(124, 122, 133);")
        self.label_9.setObjectName("label_9")
        self.btnLoginPage = QtWidgets.QPushButton(self.SignupPage)
        self.btnLoginPage.setGeometry(QtCore.QRect(296, 565, 50, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnLoginPage.setFont(font)
        self.btnLoginPage.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnLoginPage.setStyleSheet("QPushButton{\n"
                                        "color: rgb(63, 61, 84);\n"
                                        "border: 0px;\n"
                                        "background-color: rgb(255, 255, 255);\n"
                                        "}\n"
                                        "QPushButton:pressed{\n"
                                        "    color: rgb(103, 100, 138);\n"
                                        "}")
        self.btnLoginPage.setCheckable(False)
        self.btnLoginPage.setAutoExclusive(False)
        self.btnLoginPage.setDefault(False)
        self.btnLoginPage.setObjectName("btnLoginPage")
        self.frame_4 = QtWidgets.QFrame(self.SignupPage)
        self.frame_4.setGeometry(QtCore.QRect(301, 188, 120, 2))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 2))
        self.frame_4.setMaximumSize(QtCore.QSize(120, 2))
        self.frame_4.setStyleSheet("background-color: rgb(231, 231, 231);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.frame_5 = QtWidgets.QFrame(self.SignupPage)
        self.frame_5.setGeometry(QtCore.QRect(50, 188, 120, 2))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 2))
        self.frame_5.setMaximumSize(QtCore.QSize(120, 2))
        self.frame_5.setStyleSheet("background-color: rgb(231, 231, 231);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.lblConfirmPassword = QtWidgets.QLabel(self.SignupPage)
        self.lblConfirmPassword.setGeometry(QtCore.QRect(81, 410, 160, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblConfirmPassword.setFont(font)
        self.lblConfirmPassword.setStyleSheet("color: rgb(63, 61, 85);")
        self.lblConfirmPassword.setObjectName("lblConfirmPassword")
        self.txtConfirmPassword_signup = QtWidgets.QLineEdit(self.SignupPage)
        self.txtConfirmPassword_signup.setGeometry(QtCore.QRect(81, 450, 311, 41))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(10)
        self.txtConfirmPassword_signup.setFont(font)
        self.txtConfirmPassword_signup.setStyleSheet("border-style: outset;\n"
                                                     "border-width: 1px;\n"
                                                     "background-color: rgb(231, 231, 231);\n"
                                                     "border-radius: 8px;\n"
                                                     "border-color: rgb(194,194,194);\n"
                                                     "padding: 4px;")
        self.txtConfirmPassword_signup.setText("")
        self.txtConfirmPassword_signup.setObjectName("txtConfirmPassword_signup")
        self.lblError_signup = QtWidgets.QLabel(self.SignupPage)
        self.lblError_signup.setGeometry(QtCore.QRect(80, 210, 310, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblError_signup.setFont(font)
        self.lblError_signup.setStyleSheet("QLabel{\n"
                                           "color: rgb(250,0,0);\n"
                                           "line-spacing: 2px;\n"
                                           "}")
        self.lblError_signup.setText("")
        self.lblError_signup.setObjectName("lblError_signup")
        self.stackPanel.addWidget(self.SignupPage)
        self.MainPage = QtWidgets.QWidget()
        self.MainPage.setObjectName("MainPage")
        self.btnMicrophoneControl = QtWidgets.QPushButton(self.MainPage)
        self.btnMicrophoneControl.setGeometry(QtCore.QRect(196, 21, 80, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnMicrophoneControl.sizePolicy().hasHeightForWidth())
        self.btnMicrophoneControl.setSizePolicy(sizePolicy)
        self.btnMicrophoneControl.setMaximumSize(QtCore.QSize(100, 100))
        self.btnMicrophoneControl.setStyleSheet("QPushButton{\n"
                                                "background-color: rgb(62, 60, 84);\n"
                                                "border: 1px solid white;\n"
                                                "border-radius: 40;\n"
                                                "}\n"
                                                "QPushButton:pressed{\n"
                                                "    background-color: rgb(103, 100, 138);\n"
                                                "}")
        self.btnMicrophoneControl.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Icons/Icon ionic-ios-mic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnMicrophoneControl.setIcon(icon2)
        self.btnMicrophoneControl.setIconSize(QtCore.QSize(32, 32))
        self.btnMicrophoneControl.setObjectName("btnMicrophoneControl")
        self.label_5 = QtWidgets.QLabel(self.MainPage)
        self.label_5.setGeometry(QtCore.QRect(20, 150, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(19)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lblLiveTranscript = QtWidgets.QLabel(self.MainPage)
        self.lblLiveTranscript.setGeometry(QtCore.QRect(20, 190, 441, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.lblLiveTranscript.setFont(font)
        self.lblLiveTranscript.setStyleSheet("color:rgb(63, 61, 84);\n"
                                             "")
        self.lblLiveTranscript.setObjectName("lblLiveTranscript")
        self.stackPanel.addWidget(self.MainPage)
        self.TasksPage = QtWidgets.QWidget()
        self.TasksPage.setObjectName("TasksPage")
        self.scrollArea = QtWidgets.QScrollArea(self.TasksPage)
        self.scrollArea.setGeometry(QtCore.QRect(10, 10, 491, 641))
        self.scrollArea.setStyleSheet("QScrollBar:vertical{\n"
                                      "    border: none;\n"
                                      "    width: 14px;\n"
                                      "}\n"
                                      "QScrollBar::handle:vertical{\n"
                                      "    background-color: rgb(85, 255, 0);\n"
                                      "    min-height: 30px;\n"
                                      "    width: 14px;\n"
                                      "    border-radius: 7px;\n"
                                      "}\n"
                                      "")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 491, 641))
        self.scrollAreaWidgetContents.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_4.setContentsMargins(12, 0, 0, 0)
        self.verticalLayout_4.setSpacing(8)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.btnCreateTask = QtWidgets.QPushButton(self.TasksPage)
        self.btnCreateTask.setGeometry(QtCore.QRect(410, 599, 50, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCreateTask.sizePolicy().hasHeightForWidth())
        self.btnCreateTask.setSizePolicy(sizePolicy)
        self.btnCreateTask.setMaximumSize(QtCore.QSize(100, 100))
        self.btnCreateTask.setStyleSheet("QPushButton{\n"
                                         "background-color: rgb(62, 60, 84);\n"
                                         "border: 1px solid white;\n"
                                         "border-radius: 25 ;\n"
                                         "}\n"
                                         "QPushButton:pressed{\n"
                                         "    background-color: rgb(103, 100, 138);\n"
                                         "}")
        self.btnCreateTask.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Icons/Icon ionic-ios-add@2x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCreateTask.setIcon(icon3)
        self.btnCreateTask.setIconSize(QtCore.QSize(32, 32))
        self.btnCreateTask.setObjectName("btnCreateTask")
        self.stackPanel.addWidget(self.TasksPage)
        self.AddTaskPage = QtWidgets.QWidget()
        self.AddTaskPage.setObjectName("AddTaskPage")
        self.txtTitle = QtWidgets.QLineEdit(self.AddTaskPage)
        self.txtTitle.setGeometry(QtCore.QRect(39, 110, 420, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.txtTitle.setFont(font)
        self.txtTitle.setStyleSheet("border: 1px solid;\n"
                                    "border-color: rgb(62, 60, 84);")
        self.txtTitle.setMaxLength(25)
        self.txtTitle.setObjectName("txtTitle")
        self.lblTitle = QtWidgets.QLabel(self.AddTaskPage)
        self.lblTitle.setGeometry(QtCore.QRect(40, 60, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        font.setItalic(False)
        self.lblTitle.setFont(font)
        self.lblTitle.setObjectName("lblTitle")
        self.btnTaskListener = QtWidgets.QPushButton(self.AddTaskPage)
        self.btnTaskListener.setGeometry(QtCore.QRect(210, 321, 80, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnTaskListener.sizePolicy().hasHeightForWidth())
        self.btnTaskListener.setSizePolicy(sizePolicy)
        self.btnTaskListener.setMaximumSize(QtCore.QSize(100, 100))
        self.btnTaskListener.setStyleSheet("QPushButton{\n"
                                           "background-color: rgb(62, 60, 84);\n"
                                           "border: 1px solid white;\n"
                                           "border-radius: 40;\n"
                                           "}\n"
                                           "QPushButton:pressed{\n"
                                           "    background-color: rgb(103, 100, 138);\n"
                                           "}")
        self.btnTaskListener.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Icons/Icon awesome-play@2x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnTaskListener.setIcon(icon4)
        self.btnTaskListener.setIconSize(QtCore.QSize(32, 32))
        self.btnTaskListener.setObjectName("btnTaskListener")
        self.lblDescription = QtWidgets.QLabel(self.AddTaskPage)
        self.lblDescription.setGeometry(QtCore.QRect(40, 170, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        font.setItalic(False)
        self.lblDescription.setFont(font)
        self.lblDescription.setObjectName("lblDescription")
        self.txtDescription = QtWidgets.QLineEdit(self.AddTaskPage)
        self.txtDescription.setGeometry(QtCore.QRect(39, 220, 420, 30))
        self.txtDescription.setStyleSheet("border: 1px solid;\n"
                                          "border-color: rgb(62, 60, 84);")
        self.txtDescription.setMaxLength(40)
        self.txtDescription.setObjectName("txtDescription")
        self.btnAddTask = QtWidgets.QPushButton(self.AddTaskPage)
        self.btnAddTask.setGeometry(QtCore.QRect(100, 460, 311, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnAddTask.setFont(font)
        self.btnAddTask.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnAddTask.setStyleSheet("QPushButton{\n"
                                      "color: rgb(255, 255, 255);\n"
                                      "background-color: rgb(63, 61, 84);\n"
                                      "border: 2px solid  rgb(63, 61, 94);\n"
                                      "border-radius: 8px;\n"
                                      "padding: 4px;\n"
                                      "box-shadow: 0 2px 2px 0 rgba(0, 0, 0, 0.16), 0 0 0 1px rgba(0, 0, 0, 0.08);\n"
                                      "}\n"
                                      "QPushButton:pressed{\n"
                                      "    background-color: rgb(103, 100, 138);\n"
                                      "}")
        self.btnAddTask.setObjectName("btnAddTask")
        self.lblRecordTask = QtWidgets.QLabel(self.AddTaskPage)
        self.lblRecordTask.setGeometry(QtCore.QRect(40, 271, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        font.setItalic(False)
        self.lblRecordTask.setFont(font)
        self.lblRecordTask.setObjectName("lblRecordTask")
        self.btnBackToTasks = QtWidgets.QPushButton(self.AddTaskPage)
        self.btnBackToTasks.setGeometry(QtCore.QRect(10, 10, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnBackToTasks.sizePolicy().hasHeightForWidth())
        self.btnBackToTasks.setSizePolicy(sizePolicy)
        self.btnBackToTasks.setMaximumSize(QtCore.QSize(100, 100))
        self.btnBackToTasks.setStyleSheet("QPushButton{\n"
                                          "background-color: rgb(255, 255, 255);\n"
                                          "border: 1px solid white;\n"
                                          "border-radius: 20;\n"
                                          "}\n"
                                          "")
        self.btnBackToTasks.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("Icons/Icon awesome-arrow-left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnBackToTasks.setIcon(icon5)
        self.btnBackToTasks.setIconSize(QtCore.QSize(32, 32))
        self.btnBackToTasks.setObjectName("btnBackToTasks")
        self.stackPanel.addWidget(self.AddTaskPage)
        self.title_bar_2 = QtWidgets.QFrame(main)
        self.title_bar_2.setGeometry(QtCore.QRect(0, 0, 501, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title_bar_2.sizePolicy().hasHeightForWidth())
        self.title_bar_2.setSizePolicy(sizePolicy)
        self.title_bar_2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.title_bar_2.setStyleSheet("background-color: none;")
        self.title_bar_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.title_bar_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_bar_2.setObjectName("title_bar_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.title_bar_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnMenu = QtWidgets.QPushButton(self.title_bar_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnMenu.sizePolicy().hasHeightForWidth())
        self.btnMenu.setSizePolicy(sizePolicy)
        self.btnMenu.setStyleSheet("QPushButton{\n"
                                   "background-color: rgb(63, 61, 85);\n"
                                   "border: 0px solid rgb(63, 61, 85);}\n"
                                   "QPushButton:hover{\n"
                                   "    background-color: rgb(103, 100, 138);\n"
                                   "}\n"
                                   "")
        self.btnMenu.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("Icons/Icon ionic-ios-settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnMenu.setIcon(icon6)
        self.btnMenu.setIconSize(QtCore.QSize(12, 12))
        self.btnMenu.setObjectName("btnMenu")
        self.horizontalLayout_2.addWidget(self.btnMenu)
        self.frame_title = QtWidgets.QFrame(self.title_bar_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_title.sizePolicy().hasHeightForWidth())
        self.frame_title.setSizePolicy(sizePolicy)
        self.frame_title.setMinimumSize(QtCore.QSize(10, 50))
        font = QtGui.QFont()
        font.setFamily("Roboto Condensed Light")
        font.setPointSize(14)
        self.frame_title.setFont(font)
        self.frame_title.setStyleSheet("border:none;\n"
                                       "background-color: rgb(62, 60, 84);")
        self.frame_title.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_title.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_title.setObjectName("frame_title")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_title)
        self.verticalLayout_2.setContentsMargins(0, 0, 350, 20)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2.addWidget(self.frame_title)
        self.horizontalLayout.addLayout(self.horizontalLayout_2)
        self.frame_btns = QtWidgets.QFrame(self.title_bar_2)
        self.frame_btns.setMaximumSize(QtCore.QSize(100, 16777215))
        self.frame_btns.setStyleSheet("border:none;")
        self.frame_btns.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_btns.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_btns.setObjectName("frame_btns")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_btns)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btnWindowMinimize = QtWidgets.QPushButton(self.frame_btns)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnWindowMinimize.sizePolicy().hasHeightForWidth())
        self.btnWindowMinimize.setSizePolicy(sizePolicy)
        self.btnWindowMinimize.setMinimumSize(QtCore.QSize(10, 20))
        self.btnWindowMinimize.setStyleSheet("QPushButton{\n"
                                             "background-color: rgb(63, 61, 85);\n"
                                             "border: 0px solid rgb(63, 61, 85);}\n"
                                             "QPushButton:hover{\n"
                                             "    background-color: rgb(103, 100, 138);\n"
                                             "}\n"
                                             "")
        self.btnWindowMinimize.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("Icons/Icon awesome-window-minimize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnWindowMinimize.setIcon(icon7)
        self.btnWindowMinimize.setIconSize(QtCore.QSize(8, 8))
        self.btnWindowMinimize.setObjectName("btnWindowMinimize")
        self.horizontalLayout_3.addWidget(self.btnWindowMinimize)
        self.btnWindowClose = QtWidgets.QPushButton(self.frame_btns)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnWindowClose.sizePolicy().hasHeightForWidth())
        self.btnWindowClose.setSizePolicy(sizePolicy)
        self.btnWindowClose.setMinimumSize(QtCore.QSize(10, 20))
        self.btnWindowClose.setStyleSheet("QPushButton{\n"
                                          "background-color: rgb(63, 61, 85);\n"
                                          "border: 0px solid rgb(63, 61, 85);\n"
                                          "}\n"
                                          "QPushButton:hover{\n"
                                          "    \n"
                                          "    background-color: rgb(255, 0, 0);\n"
                                          "}")
        self.btnWindowClose.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("Icons/Icon ionic-ios-close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnWindowClose.setIcon(icon8)
        self.btnWindowClose.setIconSize(QtCore.QSize(8, 8))
        self.btnWindowClose.setObjectName("btnWindowClose")
        self.horizontalLayout_3.addWidget(self.btnWindowClose)
        self.horizontalLayout.addWidget(self.frame_btns)
        self.frame = QtWidgets.QFrame(main)
        self.frame.setGeometry(QtCore.QRect(-1, 29, 501, 651))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.waitingSpinner = QtWaitingSpinner(self.frame)
        self.waitingSpinner.start()
        self.SubMenuFrame = QtWidgets.QFrame(main)
        self.SubMenuFrame.setGeometry(QtCore.QRect(0, 29, 160, 80))
        self.SubMenuFrame.setStyleSheet("background-color: rgb(62, 60, 84);")
        self.SubMenuFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.SubMenuFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SubMenuFrame.setObjectName("SubMenuFrame")
        self.btnSettings = QtWidgets.QPushButton(self.SubMenuFrame)
        self.btnSettings.setGeometry(QtCore.QRect(0, -1, 160, 40))
        self.btnSettings.setStyleSheet("QPushButton{\n"
                                       "border: None;\n"
                                       "font: 100 14px  \"Segoe UI\";\n"
                                       "font-weight: 500;\n"
                                       "color: white;\n"
                                       "padding-right: 16px;\n"
                                       "}\n"
                                       "QPushButton:hover{\n"
                                       "background-color: rgb(99, 96, 134);\n"
                                       "}\n"
                                       "\n"
                                       "")
        self.btnSettings.setIcon(icon6)
        self.btnSettings.setCheckable(False)
        self.btnSettings.setObjectName("btnSettings")
        self.btnLogout = QtWidgets.QPushButton(self.SubMenuFrame)
        self.btnLogout.setGeometry(QtCore.QRect(0, 40, 160, 40))
        self.btnLogout.setStyleSheet("QPushButton{\n"
                                     "border: None;\n"
                                     "font: 100 14px  \"Segoe UI\";\n"
                                     "font-weight: 500;\n"
                                     "color: white;\n"
                                     "padding-right: 20px;\n"
                                     "}\n"
                                     "QPushButton:hover{\n"
                                     "background-color: rgb(99, 96, 134);\n"
                                     "}\n"
                                     "")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("Icons/Icon open-account-logout@2x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnLogout.setIcon(icon9)
        self.btnLogout.setObjectName("btnLogout")
        self.frame.raise_()
        self.title_bar_2.raise_()
        self.SubMenuFrame.raise_()
        self.stackPanel.raise_()

        self.retranslateUi(main)
        self.stackPanel.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(main)
        main.setTabOrder(self.btnFacebook, self.btnGoogle)
        main.setTabOrder(self.btnGoogle, self.txtEmail_login)
        main.setTabOrder(self.txtEmail_login, self.txtPassword_login)
        main.setTabOrder(self.txtPassword_login, self.chkRememberme)
        main.setTabOrder(self.chkRememberme, self.btnForgotpwd)
        main.setTabOrder(self.btnForgotpwd, self.btnLogin)
        main.setTabOrder(self.btnLogin, self.btnSignupPage)
        main.setTabOrder(self.btnSignupPage, self.btnFacebookSignup)
        main.setTabOrder(self.btnFacebookSignup, self.btnGoogleSignup)
        main.setTabOrder(self.btnGoogleSignup, self.txtEmail_signup)
        main.setTabOrder(self.txtEmail_signup, self.txtPassword_signup)
        main.setTabOrder(self.txtPassword_signup, self.txtConfirmPassword_signup)
        main.setTabOrder(self.txtConfirmPassword_signup, self.btnSignup)
        main.setTabOrder(self.btnSignup, self.btnLoginPage)
        main.setTabOrder(self.btnLoginPage, self.btnWindowMinimize)
        main.setTabOrder(self.btnWindowMinimize, self.btnWindowClose)
        main.setTabOrder(self.btnWindowClose, self.btnMicrophoneControl)

    def retranslateUi(self, main):
        _translate = QtCore.QCoreApplication.translate
        main.setWindowTitle(_translate("main", "main"))
        self.txtEmail_login.setPlaceholderText(_translate("main", "email@example.com"))
        self.label_3.setText(_translate("main", "Log in"))
        self.chkRememberme.setText(_translate("main", "Remember Me"))
        self.label_4.setText(_translate("main", "or via E-mail"))
        self.txtPassword_login.setPlaceholderText(_translate("main", "Password"))
        self.btnForgotpwd.setText(_translate("main", "Forgot Password?"))
        self.lblEmail_2.setText(_translate("main", "Email"))
        self.lblPassword_2.setText(_translate("main", "Password"))
        self.btnLogin.setText(_translate("main", "Log in"))
        self.label_10.setText(_translate("main", "Don\'t  have an account?"))
        self.btnSignupPage.setText(_translate("main", "Signup"))
        self.label_2.setText(_translate("main", "or via E-mail"))
        self.txtEmail_signup.setPlaceholderText(_translate("main", "email@example.com"))
        self.label.setText(_translate("main", "Sign Up"))
        self.txtPassword_signup.setPlaceholderText(_translate("main", "Password"))
        self.lblEmail.setText(_translate("main", "Email"))
        self.lblPassword.setText(_translate("main", "Password"))
        self.btnSignup.setText(_translate("main", "Sign Up"))
        self.label_9.setText(_translate("main", "Already have an account?"))
        self.btnLoginPage.setText(_translate("main", "Login"))
        self.lblConfirmPassword.setText(_translate("main", "Confirm Password"))
        self.txtConfirmPassword_signup.setPlaceholderText(_translate("main", "Confirm Password"))
        self.label_5.setText(_translate("main", "Transcript"))
        self.lblLiveTranscript.setText(_translate("main", "boilerplate code"))
        self.txtTitle.setPlaceholderText(_translate("main", "Title"))
        self.lblTitle.setText(_translate("main", "Title"))
        self.lblDescription.setText(_translate("main", "Description"))
        self.txtDescription.setPlaceholderText(_translate("main", "Description"))
        self.btnAddTask.setText(_translate("main", "Add Task"))
        self.lblRecordTask.setText(_translate("main", "Record Task"))
        self.btnSettings.setText(_translate("main", "  Settings"))
        self.btnLogout.setText(_translate("main", "   Logout"))
