# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\new_form_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QGraphicsDropShadowEffect

from Models.Appfonts import appFonts


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowFlag(QtCore.Qt.FramelessWindowHint)
        MainWindow.resize(508, 701)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainFrame = QtWidgets.QFrame(self.centralwidget)
        self.mainFrame.setGeometry(QtCore.QRect(0, 0, 511, 701))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainFrame.sizePolicy().hasHeightForWidth())
        self.mainFrame.setSizePolicy(sizePolicy)
        self.mainFrame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.mainFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainFrame.setObjectName("mainFrame")
        self.title_bar = QtWidgets.QFrame(self.mainFrame)
        self.title_bar.setGeometry(QtCore.QRect(0, 0, 509, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title_bar.sizePolicy().hasHeightForWidth())
        self.title_bar.setSizePolicy(sizePolicy)
        self.title_bar.setMaximumSize(QtCore.QSize(16777215, 30))
        self.title_bar.setStyleSheet("background-color: none;")
        self.title_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.title_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        # shadow = QGraphicsDropShadowEffect(blurRadius=7, xOffset=4, yOffset=1)
        # self.title_bar.setGraphicsEffect(shadow)
        self.title_bar.setObjectName("title_bar")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.title_bar)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btnMenu = QtWidgets.QPushButton(self.title_bar)
        self.btnMenu.setFocusPolicy(QtCore.Qt.NoFocus)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnMenu.sizePolicy().hasHeightForWidth())
        self.btnMenu.setSizePolicy(sizePolicy)
        self.btnMenu.setMinimumSize(QtCore.QSize(35, 30))
        self.btnMenu.setStyleSheet("QPushButton{\n"
                                   "background:  url(Icons/Menu Icon.png) no-repeat center center fixed;\n"
                                   "background-color: rgb(63, 61, 85);\n"
                                   "border: 0px solid rgb(63, 61, 85);\n"
                                   "}\n"
                                   "QPushButton:hover{\n"
                                   "    background-color: rgb(103, 100, 138);\n"
                                   "}\n"
                                   "")
        self.btnMenu.setText("")
        self.btnMenu.setIconSize(QtCore.QSize(12, 12))
        self.btnMenu.setObjectName("btnMenu")
        self.horizontalLayout_5.addWidget(self.btnMenu)
        self.frame_title = QtWidgets.QFrame(self.title_bar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_title.sizePolicy().hasHeightForWidth())
        self.frame_title.setSizePolicy(sizePolicy)
        self.frame_title.setMinimumSize(QtCore.QSize(10, 50))
        font = QtGui.QFont()
        font.setFamily("Roboto Condensed Light")
        font.setPointSize(14)
        self.frame_title.setFont(font)
        self.frame_title.setStyleSheet("border:none;\n"
                                       "background-color: rgb(62, 60, 84);")
        self.frame_title.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_title.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_title.setObjectName("frame_title")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_title)
        self.verticalLayout_3.setContentsMargins(0, 0, 350, 20)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_5.addWidget(self.frame_title)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_5)
        self.frame_btns = QtWidgets.QFrame(self.title_bar)
        self.frame_btns.setMaximumSize(QtCore.QSize(100, 16777215))
        self.frame_btns.setStyleSheet("border:none;")
        self.frame_btns.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_btns.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_btns.setObjectName("frame_btns")
        self.frame_btns.setFocusPolicy(QtCore.Qt.NoFocus)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_btns)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.btnWindowMinimize = QtWidgets.QPushButton(self.frame_btns)
        self.btnWindowMinimize.setFocusPolicy(QtCore.Qt.NoFocus)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnWindowMinimize.sizePolicy().hasHeightForWidth())
        self.btnWindowMinimize.setSizePolicy(sizePolicy)
        self.btnWindowMinimize.setMinimumSize(QtCore.QSize(10, 20))
        self.btnWindowMinimize.setStyleSheet("QPushButton{\n"
                                             "background-color: rgb(63, 61, 85);\n"
                                             "border: 0px solid rgb(63, 61, 85);}\n"
                                             "QPushButton:hover{\n"
                                             "    background-color: rgb(103, 100, 138);\n"
                                             "}\n"
                                             "")
        self.btnWindowMinimize.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\Icons/Icon awesome-window-minimize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnWindowMinimize.setIcon(icon)
        self.btnWindowMinimize.setIconSize(QtCore.QSize(8, 8))
        self.btnWindowMinimize.setObjectName("btnWindowMinimize")
        self.horizontalLayout_6.addWidget(self.btnWindowMinimize)
        self.btnWindowClose = QtWidgets.QPushButton(self.frame_btns)
        self.btnWindowClose.setFocusPolicy(QtCore.Qt.NoFocus)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnWindowClose.sizePolicy().hasHeightForWidth())
        self.btnWindowClose.setSizePolicy(sizePolicy)
        self.btnWindowClose.setMinimumSize(QtCore.QSize(10, 20))
        self.btnWindowClose.setStyleSheet("QPushButton{\n"
                                          "background-color: rgb(63, 61, 85);\n"
                                          "border: 0px solid rgb(63, 61, 85);\n"
                                          "}\n"
                                          "QPushButton:hover{\n"
                                          "    \n"
                                          "    background-color: rgb(255, 0, 0);\n"
                                          "}")
        self.btnWindowClose.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(".\\Icons/Icon ionic-ios-close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnWindowClose.setIcon(icon1)
        self.btnWindowClose.setIconSize(QtCore.QSize(8, 8))
        self.btnWindowClose.setFlat(False)
        self.btnWindowClose.setObjectName("btnWindowClose")
        self.horizontalLayout_6.addWidget(self.btnWindowClose)
        self.horizontalLayout_4.addWidget(self.frame_btns)
        self.stackPanel = QtWidgets.QStackedWidget(self.mainFrame)
        self.stackPanel.setGeometry(QtCore.QRect(0, 30, 509, 669))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.stackPanel.setFont(font)
        self.stackPanel.setStyleSheet("border:none\n"
                                      "")
        self.stackPanel.setObjectName("stackPanel")
        self.LoginPage = QtWidgets.QWidget()
        self.LoginPage.setObjectName("LoginPage")
        self.loginMainFrame = QtWidgets.QFrame(self.LoginPage)
        self.loginMainFrame.setGeometry(QtCore.QRect(0, 0, 511, 631))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loginMainFrame.sizePolicy().hasHeightForWidth())
        self.loginMainFrame.setSizePolicy(sizePolicy)
        self.loginMainFrame.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.loginMainFrame.setStyleSheet("")
        self.loginMainFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.loginMainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.loginMainFrame.setObjectName("loginMainFrame")
        self.VLayoutLogin = QtWidgets.QVBoxLayout(self.loginMainFrame)
        self.VLayoutLogin.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.VLayoutLogin.setContentsMargins(0, 20, 0, 0)
        self.VLayoutLogin.setSpacing(0)
        self.VLayoutLogin.setObjectName("VLayoutLogin")
        self.lblLogin = QtWidgets.QLabel(self.loginMainFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblLogin.sizePolicy().hasHeightForWidth())
        self.lblLogin.setSizePolicy(sizePolicy)
        self.lblLogin.setFont(appFonts.getAuthHeadingFont())
        self.lblLogin.setStyleSheet("QLabel{\n"
                                    "color:rgb(63, 61, 84);\n"
                                    "margin-left: 50%;\n"
                                    "margin-right: 50%;\n"
                                    "\n"
                                    "}")
        self.lblLogin.setAlignment(QtCore.Qt.AlignCenter)
        self.lblLogin.setObjectName("lblLogin")
        self.VLayoutLogin.addWidget(self.lblLogin)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_10.setContentsMargins(100, 40, 100, 20)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.btnFacebook = QtWidgets.QPushButton(self.loginMainFrame)
        self.btnFacebook.setFocusPolicy(QtCore.Qt.NoFocus)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnFacebook.sizePolicy().hasHeightForWidth())
        self.btnFacebook.setSizePolicy(sizePolicy)
        self.btnFacebook.setMinimumSize(QtCore.QSize(55, 55))
        self.btnFacebook.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnFacebook.setAutoFillBackground(False)
        self.btnFacebook.setStyleSheet("QPushButton{\n"
                                       "color: #333;\n"
                                       "border: 0px solid  rgb(231, 231, 231);\n"
                                       "background-color: rgb(231, 231, 231);\n"
                                       "border-radius: 12px;\n"
                                       "color:rgb(240, 240, 240)\n"
                                       "}\n"
                                       "QPushButton:pressed{\n"
                                       "background-color: rgb(240, 240, 240);\n"
                                       "border-color: rgb(240, 240, 240);\n"
                                       "}")
        self.btnFacebook.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(".\\Icons/icons8-facebook-circled-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnFacebook.setIcon(icon2)
        self.btnFacebook.setIconSize(QtCore.QSize(32, 32))
        self.btnFacebook.setObjectName("btnFacebook")
        self.horizontalLayout_10.addWidget(self.btnFacebook)
        self.btnGoogle = QtWidgets.QPushButton(self.loginMainFrame)
        self.btnGoogle.setFocusPolicy(QtCore.Qt.NoFocus)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnGoogle.sizePolicy().hasHeightForWidth())
        self.btnGoogle.setSizePolicy(sizePolicy)
        self.btnGoogle.setMinimumSize(QtCore.QSize(55, 55))
        self.btnGoogle.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnGoogle.setAutoFillBackground(False)
        self.btnGoogle.setStyleSheet("QPushButton{\n"
                                     "color: #333;\n"
                                     "border: 0px solid  rgb(231, 231, 231);\n"
                                     "background-color: rgb(231, 231, 231);\n"
                                     "border-radius: 12px;\n"
                                     "color:rgb(240, 240, 240)\n"
                                     "}\n"
                                     "QPushButton:pressed{\n"
                                     "background-color: rgb(240, 240, 240);\n"
                                     "border-color: rgb(240, 240, 240);\n"
                                     "}")
        self.btnGoogle.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(".\\Icons/icons8-google-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnGoogle.setIcon(icon3)
        self.btnGoogle.setIconSize(QtCore.QSize(32, 32))
        self.btnGoogle.setObjectName("btnGoogle")
        self.horizontalLayout_10.addWidget(self.btnGoogle)
        self.verticalLayout_8.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_11.setContentsMargins(0, 20, 0, 0)
        self.horizontalLayout_11.setSpacing(12)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem)
        self.dividerFrame_login_1 = QtWidgets.QFrame(self.loginMainFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dividerFrame_login_1.sizePolicy().hasHeightForWidth())
        self.dividerFrame_login_1.setSizePolicy(sizePolicy)
        self.dividerFrame_login_1.setMinimumSize(QtCore.QSize(100, 2))
        self.dividerFrame_login_1.setMaximumSize(QtCore.QSize(100, 2))
        self.dividerFrame_login_1.setStyleSheet("background-color: rgb(112, 112, 112);")
        self.dividerFrame_login_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dividerFrame_login_1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.dividerFrame_login_1.setObjectName("dividerFrame_login_1")
        self.horizontalLayout_11.addWidget(self.dividerFrame_login_1)
        self.lblorviaEmail_login = QtWidgets.QLabel(self.loginMainFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblorviaEmail_login.sizePolicy().hasHeightForWidth())
        self.lblorviaEmail_login.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lblorviaEmail_login.setFont(font)
        self.lblorviaEmail_login.setStyleSheet("color: rgb(194, 194, 194);\n"
                                               "padding-bottom: 4px;\n"
                                               "font-weight: 600;")
        self.lblorviaEmail_login.setAlignment(QtCore.Qt.AlignCenter)
        self.lblorviaEmail_login.setObjectName("lblorviaEmail_login")
        self.horizontalLayout_11.addWidget(self.lblorviaEmail_login)
        self.dividerFrame_login_2 = QtWidgets.QFrame(self.loginMainFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dividerFrame_login_2.sizePolicy().hasHeightForWidth())
        self.dividerFrame_login_2.setSizePolicy(sizePolicy)
        self.dividerFrame_login_2.setMinimumSize(QtCore.QSize(100, 2))
        self.dividerFrame_login_2.setMaximumSize(QtCore.QSize(100, 2))
        self.dividerFrame_login_2.setStyleSheet("background-color: rgb(112, 112, 112);")
        self.dividerFrame_login_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dividerFrame_login_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.dividerFrame_login_2.setObjectName("dividerFrame_login_2")
        self.horizontalLayout_11.addWidget(self.dividerFrame_login_2)
        spacerItem1 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem1)
        self.verticalLayout_8.addLayout(self.horizontalLayout_11)
        self.lblError_login = QtWidgets.QLabel(self.loginMainFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblError_login.sizePolicy().hasHeightForWidth())
        self.lblError_login.setSizePolicy(sizePolicy)
        self.lblError_login.setAlignment(QtCore.Qt.AlignHCenter)
        self.lblError_login.setFont(appFonts.getErrorFont())
        self.lblError_login.setStyleSheet("QLabel{\n"
                                          "color: rgb(250,0,0);\n"
                                          "line-spacing: 2px;\n"
                                          "}")
        self.lblError_login.setText("")
        self.lblError_login.setObjectName("lblError_login")
        self.verticalLayout_8.addWidget(self.lblError_login)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_2.setRowWrapPolicy(QtWidgets.QFormLayout.DontWrapRows)
        self.formLayout_2.setLabelAlignment(QtCore.Qt.AlignJustify | QtCore.Qt.AlignVCenter)
        self.formLayout_2.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_2.setContentsMargins(12, -1, 12, 30)
        self.formLayout_2.setHorizontalSpacing(0)
        self.formLayout_2.setVerticalSpacing(12)
        self.formLayout_2.setObjectName("formLayout_2")
        self.lblEmail = QtWidgets.QLabel(self.loginMainFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEmail.sizePolicy().hasHeightForWidth())
        self.lblEmail.setSizePolicy(sizePolicy)
        self.lblEmail.setMinimumSize(QtCore.QSize(51, 21))
        self.lblEmail.setFont(appFonts.getFormHeadingFont())
        self.lblEmail.setStyleSheet("color: rgb(63, 61, 85);")
        self.lblEmail.setObjectName("lblEmail")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblEmail)
        self.txtEmail_login = QtWidgets.QLineEdit(self.loginMainFrame)
        self.txtEmail_login.setMinimumSize(QtCore.QSize(311, 41))
        self.txtEmail_login.setFont(appFonts.getLineEditFont())
        self.txtEmail_login.setStyleSheet("border-style: outset;\n"
                                          "border-width: 1px;\n"
                                          "background-color: rgb(231, 231, 231);\n"
                                          "border-radius: 8px;\n"
                                          "border-color: rgb(194,194,194);\n"
                                          
                                          "padding: 4px;")
        self.txtEmail_login.setText("")
        self.txtEmail_login.setObjectName("txtEmail_login")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.txtEmail_login)
        self.lblPassword = QtWidgets.QLabel(self.loginMainFrame)
        self.lblPassword.setMinimumSize(QtCore.QSize(51, 21))
        self.lblPassword.setFont(appFonts.getFormHeadingFont())
        self.lblPassword.setStyleSheet("color: rgb(63, 61, 85);")
        self.lblPassword.setObjectName("lblPassword")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lblPassword)
        self.txtPassword_login = QtWidgets.QLineEdit(self.loginMainFrame)
        self.txtPassword_login.setMinimumSize(QtCore.QSize(311, 41))
        self.txtPassword_login.setFont(appFonts.getLineEditFont())
        self.txtPassword_login.setStyleSheet("border-style: outset;\n"
                                             "border-width: 1px;\n"
                                             "background-color: rgb(231, 231, 231);\n"
                                             "border-radius: 8px;\n"
                                             "border-color: rgb(194,194,194);\n"
                                             
                                             "padding: 4px;")
        self.txtPassword_login.setText("")
        self.txtPassword_login.setObjectName("txtPassword_login")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.txtPassword_login)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setSpacing(100)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.chkRememberme = QtWidgets.QCheckBox(self.loginMainFrame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.chkRememberme.setFont(font)
        self.chkRememberme.setStyleSheet("color: rgb(124, 122, 133);")
        self.chkRememberme.setObjectName("chkRememberme")
        self.horizontalLayout_13.addWidget(self.chkRememberme)
        self.btnForgotpwd = QtWidgets.QPushButton(self.loginMainFrame)
        self.btnForgotpwd.setFocusPolicy(QtCore.Qt.NoFocus)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnForgotpwd.sizePolicy().hasHeightForWidth())
        self.btnForgotpwd.setSizePolicy(sizePolicy)
        self.btnForgotpwd.setFont(appFonts.getLinkButtonFont())
        self.btnForgotpwd.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnForgotpwd.setStyleSheet("QPushButton{\n"
                                        "color: rgb(63, 61, 84);\n"
                                        "border: 0px;\n"
                                        "background-color: rgb(255, 255, 255);\n"
                                        "}\n"
                                        "QPushButton:pressed{\n"
                                        "    color: rgb(103, 100, 138);\n"
                                        "}")
        self.btnForgotpwd.setObjectName("btnForgotpwd")
        self.horizontalLayout_13.addWidget(self.btnForgotpwd)
        self.formLayout_2.setLayout(4, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_13)
        self.btnLogin = QtWidgets.QPushButton(self.loginMainFrame)
        self.btnLogin.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnLogin.setMinimumSize(QtCore.QSize(311, 41))
        self.btnLogin.setFont(appFonts.getAuthButtonFont())
        self.btnLogin.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnLogin.setStyleSheet("QPushButton{\n"
                                    "color: rgb(255, 255, 255);\n"
                                    "background-color: rgb(63, 61, 84);\n"
                                    "border: 2px solid  rgb(63, 61, 94);\n"
                                    "border-radius: 8px;\n"
                                    "padding: 4px;\n"
                                    "box-shadow: 0 2px 2px 0 rgba(0, 0, 0, 0.16), 0 0 0 1px rgba(0, 0, 0, 0.08);\n"
                                    "}\n"
                                    "QPushButton:pressed{\n"
                                    "background-color: rgb(103, 100, 138);\n"
                                     "border: 2px solid  rgb(103, 100, 138);\n"
                                     "border-radius: 8px;\n"
                                     "padding: 4px;\n"
                                    "}")
        self.btnLogin.setObjectName("btnLogin")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.btnLogin)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setContentsMargins(30, -1, -1, -1)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem3)
        self.lblDontHaveAnAccount = QtWidgets.QLabel(self.loginMainFrame)
        self.lblDontHaveAnAccount.setMinimumSize(QtCore.QSize(110, 31))
        self.lblDontHaveAnAccount.setFont(appFonts.getLightFont())
        self.lblDontHaveAnAccount.setStyleSheet("color: rgb(124, 122, 133);")
        self.lblDontHaveAnAccount.setObjectName("lblDontHaveAnAccount")
        self.horizontalLayout_12.addWidget(self.lblDontHaveAnAccount)
        self.btnSignupPage = QtWidgets.QPushButton(self.loginMainFrame)
        self.btnSignupPage.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnSignupPage.setFont(appFonts.getLinkButtonFont())
        self.btnSignupPage.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSignupPage.setStyleSheet("QPushButton{\n"
                                         "color: rgb(63, 61, 84);\n"
                                         "border: 0px;\n"
                                         "background-color: rgb(255, 255, 255);\n"
                                         "}\n"
                                         "QPushButton:pressed{\n"
                                         "    color: rgb(103, 100, 138);\n"
                                         "}")
        self.btnSignupPage.setCheckable(False)
        self.btnSignupPage.setAutoExclusive(False)
        self.btnSignupPage.setDefault(False)
        self.btnSignupPage.setObjectName("btnSignupPage")
        self.horizontalLayout_12.addWidget(self.btnSignupPage)
        spacerItem3 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem3)
        self.formLayout_2.setLayout(6, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_12)
        self.verticalLayout_8.addLayout(self.formLayout_2)
        self.VLayoutLogin.addLayout(self.verticalLayout_8)
        self.stackPanel.addWidget(self.LoginPage)
        self.SignupPage = QtWidgets.QWidget()
        self.SignupPage.setObjectName("SignupPage")
        self.signupMainFrame = QtWidgets.QFrame(self.SignupPage)
        self.signupMainFrame.setGeometry(QtCore.QRect(0, 0, 511, 631))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.signupMainFrame.sizePolicy().hasHeightForWidth())
        self.signupMainFrame.setSizePolicy(sizePolicy)
        self.signupMainFrame.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.signupMainFrame.setStyleSheet("")
        self.signupMainFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.signupMainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.signupMainFrame.setObjectName("signupMainFrame")
        self.VLayoutSignup = QtWidgets.QVBoxLayout(self.signupMainFrame)
        self.VLayoutSignup.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.VLayoutSignup.setContentsMargins(0, 20, 0, 0)
        self.VLayoutSignup.setSpacing(0)
        self.VLayoutSignup.setObjectName("VLayoutSignup")
        self.lblSignup = QtWidgets.QLabel(self.signupMainFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblSignup.sizePolicy().hasHeightForWidth())
        self.lblSignup.setSizePolicy(sizePolicy)
        self.lblSignup.setFont(appFonts.getAuthHeadingFont())
        self.lblSignup.setStyleSheet("QLabel{\n"
                                     "color:rgb(63, 61, 84);\n"
                                     "margin-left: 50%;\n"
                                     "margin-right: 50%;\n"
                                     "\n"
                                     "}")
        self.lblSignup.setAlignment(QtCore.Qt.AlignCenter)
        self.lblSignup.setObjectName("lblSignup")
        self.VLayoutSignup.addWidget(self.lblSignup)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_7.setContentsMargins(100, 40, 100, 20)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.btnFacebookSignup = QtWidgets.QPushButton(self.signupMainFrame)
        self.btnFacebookSignup.setFocusPolicy(QtCore.Qt.NoFocus)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnFacebookSignup.sizePolicy().hasHeightForWidth())
        self.btnFacebookSignup.setSizePolicy(sizePolicy)
        self.btnFacebookSignup.setMinimumSize(QtCore.QSize(55, 55))
        self.btnFacebookSignup.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnFacebookSignup.setAutoFillBackground(False)
        self.btnFacebookSignup.setStyleSheet("QPushButton{\n"
                                             "color: #333;\n"
                                             "border: 0px solid  rgb(231, 231, 231);\n"
                                             "background-color: rgb(231, 231, 231);\n"
                                             "border-radius: 12px;\n"
                                             "color:rgb(240, 240, 240)\n"
                                             "}\n"
                                             "QPushButton:pressed{\n"
                                             "background-color: rgb(240, 240, 240);\n"
                                             "border-color: rgb(240, 240, 240);\n"
                                             "}")
        self.btnFacebookSignup.setText("")
        self.btnFacebookSignup.setIcon(icon2)
        self.btnFacebookSignup.setIconSize(QtCore.QSize(32, 32))
        self.btnFacebookSignup.setObjectName("btnFacebookSignup")
        self.horizontalLayout_7.addWidget(self.btnFacebookSignup)
        self.btnGoogleSignup = QtWidgets.QPushButton(self.signupMainFrame)
        self.btnGoogleSignup.setFocusPolicy(QtCore.Qt.NoFocus)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnGoogleSignup.sizePolicy().hasHeightForWidth())
        self.btnGoogleSignup.setSizePolicy(sizePolicy)
        self.btnGoogleSignup.setMinimumSize(QtCore.QSize(55, 55))
        self.btnGoogleSignup.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnGoogleSignup.setAutoFillBackground(False)
        self.btnGoogleSignup.setStyleSheet("QPushButton{\n"
                                           "color: #333;\n"
                                           "border: 0px solid  rgb(231, 231, 231);\n"
                                           "background-color: rgb(231, 231, 231);\n"
                                           "border-radius: 12px;\n"
                                           "color:rgb(240, 240, 240)\n"
                                           "}\n"
                                           "QPushButton:pressed{\n"
                                           "background-color: rgb(240, 240, 240);\n"
                                           "border-color: rgb(240, 240, 240);\n"
                                           "}")
        self.btnGoogleSignup.setText("")
        self.btnGoogleSignup.setIcon(icon3)
        self.btnGoogleSignup.setIconSize(QtCore.QSize(32, 32))
        self.btnGoogleSignup.setObjectName("btnGoogleSignup")
        self.horizontalLayout_7.addWidget(self.btnGoogleSignup)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_8.setContentsMargins(0, 20, 0, 0)
        self.horizontalLayout_8.setSpacing(12)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem2 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.dividerFrame_signup_2 = QtWidgets.QFrame(self.signupMainFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dividerFrame_signup_2.sizePolicy().hasHeightForWidth())
        self.dividerFrame_signup_2.setSizePolicy(sizePolicy)
        self.dividerFrame_signup_2.setMinimumSize(QtCore.QSize(100, 2))
        self.dividerFrame_signup_2.setMaximumSize(QtCore.QSize(100, 2))
        self.dividerFrame_signup_2.setStyleSheet("background-color: rgb(112, 112, 112);")
        self.dividerFrame_signup_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dividerFrame_signup_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.dividerFrame_signup_2.setObjectName("dividerFrame_signup_2")
        self.horizontalLayout_8.addWidget(self.dividerFrame_signup_2)
        self.lblorviaEmail = QtWidgets.QLabel(self.signupMainFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblorviaEmail.sizePolicy().hasHeightForWidth())
        self.lblorviaEmail.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lblorviaEmail.setFont(font)
        self.lblorviaEmail.setStyleSheet("color: rgb(194, 194, 194);\n"
                                         "padding-bottom: 4px;\n"
                                         "font-weight: 600;")
        self.lblorviaEmail.setAlignment(QtCore.Qt.AlignCenter)
        self.lblorviaEmail.setObjectName("lblorviaEmail")
        self.horizontalLayout_8.addWidget(self.lblorviaEmail)
        self.dividerFrame_signup_1 = QtWidgets.QFrame(self.signupMainFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dividerFrame_signup_1.sizePolicy().hasHeightForWidth())
        self.dividerFrame_signup_1.setSizePolicy(sizePolicy)
        self.dividerFrame_signup_1.setMinimumSize(QtCore.QSize(100, 2))
        self.dividerFrame_signup_1.setMaximumSize(QtCore.QSize(100, 2))
        self.dividerFrame_signup_1.setStyleSheet("background-color: rgb(112, 112, 112);")
        self.dividerFrame_signup_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dividerFrame_signup_1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.dividerFrame_signup_1.setObjectName("dividerFrame_signup_1")
        self.horizontalLayout_8.addWidget(self.dividerFrame_signup_1)

        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.lblError_signup = QtWidgets.QLabel(self.signupMainFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblError_signup.sizePolicy().hasHeightForWidth())
        self.lblError_signup.setSizePolicy(sizePolicy)
        self.lblError_signup.setAlignment(QtCore.Qt.AlignHCenter)
        self.lblError_signup.setFont(appFonts.getErrorFont())
        self.lblError_signup.setStyleSheet("QLabel{\n"
                                           "color: rgb(250,0,0);\n"
                                           "line-spacing: 2px;\n"
                                           "}")
        self.lblError_signup.setText("")
        self.lblError_signup.setObjectName("lblError_signup")
        self.verticalLayout_6.addWidget(self.lblError_signup)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setRowWrapPolicy(QtWidgets.QFormLayout.DontWrapRows)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignJustify | QtCore.Qt.AlignVCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setContentsMargins(12, -1, 12, -1)
        self.formLayout.setHorizontalSpacing(0)
        self.formLayout.setVerticalSpacing(12)
        self.formLayout.setObjectName("formLayout")
        self.lblEmail_signup = QtWidgets.QLabel(self.signupMainFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEmail_signup.sizePolicy().hasHeightForWidth())
        self.lblEmail_signup.setSizePolicy(sizePolicy)
        self.lblEmail_signup.setMinimumSize(QtCore.QSize(51, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblEmail_signup.setFont(font)
        self.lblEmail_signup.setStyleSheet("color: rgb(63, 61, 85);")
        self.lblEmail_signup.setObjectName("lblEmail_signup")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblEmail_signup)
        self.txtEmail_signup = QtWidgets.QLineEdit(self.signupMainFrame)
        self.txtEmail_signup.setMinimumSize(QtCore.QSize(311, 41))
        self.txtEmail_signup.setFont(appFonts.getLineEditFont())
        self.txtEmail_signup.setStyleSheet("border-style: outset;\n"
                                           "background-color: rgb(231, 231, 231);\n"
                                           "border-width: 1px;\n"
                                           "border-radius: 8px;\n"
                                           "border-color: rgb(194,194,194);\n"
                                           "padding: 4px;")
        self.txtEmail_signup.setText("")
        self.txtEmail_signup.setObjectName("txtEmail_signup")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.txtEmail_signup)
        self.lblPassword_signup = QtWidgets.QLabel(self.signupMainFrame)
        self.lblPassword_signup.setMinimumSize(QtCore.QSize(51, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblPassword_signup.setFont(font)
        self.lblPassword_signup.setStyleSheet("color: rgb(63, 61, 85);")
        self.lblPassword_signup.setObjectName("lblPassword_signup")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lblPassword_signup)
        self.txtPassword_signup = QtWidgets.QLineEdit(self.signupMainFrame)
        self.txtPassword_signup.setMinimumSize(QtCore.QSize(311, 41))
        self.txtPassword_signup.setFont(appFonts.getLineEditFont())
        self.txtPassword_signup.setStyleSheet("border-style: outset;\n"
                                              "border-width: 1px;\n"
                                              "background-color: rgb(231, 231, 231);\n"
                                              "border-radius: 8px;\n"
                                              "border-color: rgb(194,194,194);\n"
                                              
                                              "padding: 4px;")
        self.txtPassword_signup.setText("")
        self.txtPassword_signup.setObjectName("txtPassword_signup")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.txtPassword_signup)
        self.lblConfirmPassword = QtWidgets.QLabel(self.signupMainFrame)
        self.lblConfirmPassword.setMinimumSize(QtCore.QSize(51, 21))
        self.lblConfirmPassword.setFont(appFonts.getFormHeadingFont())
        self.lblConfirmPassword.setStyleSheet("color: rgb(63, 61, 85);")
        self.lblConfirmPassword.setObjectName("lblConfirmPassword")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lblConfirmPassword)
        self.txtConfirmPassword_signup = QtWidgets.QLineEdit(self.signupMainFrame)
        self.txtConfirmPassword_signup.setMinimumSize(QtCore.QSize(311, 41))
        self.txtConfirmPassword_signup.setFont(appFonts.getLineEditFont())
        self.txtConfirmPassword_signup.setStyleSheet("border-style: outset;\n"
                                                     "border-width: 1px;\n"
                                                     "background-color: rgb(231, 231, 231);\n"
                                                     "border-radius: 8px;\n"
                                                     "border-color: rgb(194,194,194);\n"         
                                                     "padding: 4px;")
        self.txtConfirmPassword_signup.setText("")
        self.txtConfirmPassword_signup.setObjectName("txtConfirmPassword_signup")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.txtConfirmPassword_signup)
        self.btnSignup = QtWidgets.QPushButton(self.signupMainFrame)
        self.btnSignup.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnSignup.setMinimumSize(QtCore.QSize(311, 41))
        self.btnSignup.setFont(appFonts.getAuthButtonFont())
        self.btnSignup.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSignup.setStyleSheet("QPushButton{\n"
                                     "color: rgb(255, 255, 255);\n"
                                     "background-color: rgb(63, 61, 84);\n"
                                     "border: 2px solid  rgb(63, 61, 94);\n"
                                     "border-radius: 8px;\n"
                                     "padding: 4px;\n"
                                     "box-shadow: 0 2px 2px 0 rgba(0, 0, 0, 0.16), 0 0 0 1px rgba(0, 0, 0, 0.08);\n"
                                     "}\n"
                                     "QPushButton:pressed{\n"
                                     "background-color: rgb(103, 100, 138);\n"
                                     "border: 2px solid  rgb(103, 100, 138);\n"
                                     "border-radius: 8px;\n"
                                     "padding: 4px;\n"
                                     "}")
        self.btnSignup.setObjectName("btnSignup")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.btnSignup)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(30, -1, -1, -1)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem3)
        self.lblHaveanAccount = QtWidgets.QLabel(self.signupMainFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblHaveanAccount.sizePolicy().hasHeightForWidth())
        self.lblHaveanAccount.setSizePolicy(sizePolicy)
        self.lblHaveanAccount.setMinimumSize(QtCore.QSize(110, 31))
        self.lblHaveanAccount.setFont(appFonts.getLightFont())
        self.lblHaveanAccount.setStyleSheet("color: rgb(124, 122, 133);")
        self.lblHaveanAccount.setObjectName("lblHaveanAccount")
        self.horizontalLayout_9.addWidget(self.lblHaveanAccount)
        self.btnLoginPage = QtWidgets.QPushButton(self.signupMainFrame)
        self.btnLoginPage.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnLoginPage.setFont(appFonts.getLinkButtonFont())
        self.btnLoginPage.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnLoginPage.setStyleSheet("QPushButton{\n"
                                        "color: rgb(63, 61, 84);\n"
                                        "border : 0px;\n"
                                        "background-color: rgb(255, 255, 255);\n"
                                        "}\n"
                                        "QPushButton:pressed{\n"
                                        "    color: rgb(103, 100, 138);\n"
                                        "}")
        self.btnLoginPage.setCheckable(False)
        self.btnLoginPage.setAutoExclusive(False)
        self.btnLoginPage.setDefault(False)
        self.btnLoginPage.setObjectName("btnLoginPage")
        self.horizontalLayout_9.addWidget(self.btnLoginPage)
        spacerItem4 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.formLayout.setLayout(7, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_9)
        self.verticalLayout_6.addLayout(self.formLayout)
        self.VLayoutSignup.addLayout(self.verticalLayout_6)
        self.stackPanel.addWidget(self.SignupPage)
        self.MainPage = QtWidgets.QWidget()
        self.MainPage.setObjectName("MainPage")
        self.btnMicrophoneControl = QtWidgets.QPushButton(self.MainPage)
        self.btnMicrophoneControl.setGeometry(QtCore.QRect(196, 21, 80, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnMicrophoneControl.sizePolicy().hasHeightForWidth())
        self.btnMicrophoneControl.setSizePolicy(sizePolicy)
        self.btnMicrophoneControl.setMaximumSize(QtCore.QSize(100, 100))
        shadow = QGraphicsDropShadowEffect(blurRadius=7, xOffset=4, yOffset=1)
        self.btnMicrophoneControl.setGraphicsEffect(shadow)
        self.btnMicrophoneControl.setStyleSheet("QPushButton{\n"
                                                "background-color: rgb(62, 60, 84);\n"
                                                "border: 1px solid white;\n"
                                                "border-radius: 40;\n"
                                                "}\n"
                                                "QPushButton:pressed{\n"
                                                "background-color: rgb(255, 255, 255);\n"
                                                "}")
        self.btnMicrophoneControl.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(".\\Icons/Icon ionic-ios-mic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnMicrophoneControl.setIcon(icon4)
        self.btnMicrophoneControl.setIconSize(QtCore.QSize(32, 32))
        self.btnMicrophoneControl.setObjectName("btnMicrophoneControl")
        self.lblTranscript = QtWidgets.QLabel(self.MainPage)
        self.lblTranscript.setGeometry(QtCore.QRect(20, 150, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(19)
        font.setBold(False)
        font.setWeight(50)
        self.lblTranscript.setFont(font)
        self.lblTranscript.setObjectName("lblTranscript")
        self.lblLiveTranscript = QtWidgets.QLabel(self.MainPage)
        self.lblLiveTranscript.setGeometry(QtCore.QRect(20, 190, 441, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.lblLiveTranscript.setFont(font)
        self.lblLiveTranscript.setStyleSheet("color:rgb(63, 61, 84);\n"
                                             "")
        self.lblLiveTranscript.setObjectName("lblLiveTranscript")
        self.stackPanel.addWidget(self.MainPage)
        self.TasksPage = QtWidgets.QWidget()
        self.TasksPage.setObjectName("TasksPage")
        self.scrollArea = QtWidgets.QScrollArea(self.TasksPage)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 508, 671))
        self.scrollArea.setStyleSheet("QScrollBar:vertical{\n"
                                      "    border: none;\n"
                                      "    width: 14px;\n"
                                      "}\n"
                                      "QScrollBar::handle:vertical{\n"
                                      "    background-color: rgb(62, 60, 84);\n"
                                      "    min-height: 30px;\n"
                                      "    width: 14px;\n"
                                      "border-radius: 7px;\n"
                                      "}\n"
                                      "")
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 478, 168))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.btnCreateTask = QtWidgets.QPushButton(self.TasksPage)
        self.btnCreateTask.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnCreateTask.setGeometry(QtCore.QRect(430, 600, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCreateTask.sizePolicy().hasHeightForWidth())
        self.btnCreateTask.setSizePolicy(sizePolicy)
        self.btnCreateTask.setMaximumSize(QtCore.QSize(100, 100))
        self.btnCreateTask.setStyleSheet("QPushButton{\n"
                                         "background-color: rgb(62, 60, 84);\n"
                                         "border: none;\n"
                                         "border-radius: 30;\n"
                                         "}\n"
                                         "QPushButton:pressed{\n"
                                         "    background-color: rgb(103, 100, 138);\n"
                                         "}")
        self.btnCreateTask.setText("")
        shadow = QGraphicsDropShadowEffect(blurRadius=5, xOffset=3, yOffset=3)
        self.btnCreateTask.setGraphicsEffect(shadow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(".\\Icons/Icon ionic-ios-add@2x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCreateTask.setIcon(icon7)
        self.btnCreateTask.setIconSize(QtCore.QSize(32, 32))
        self.btnCreateTask.setObjectName("btnCreateTask")
        self.stackPanel.addWidget(self.TasksPage)
        self.AddTaskPage = QtWidgets.QWidget()
        self.AddTaskPage.setObjectName("AddTaskPage")
        self.txtTitle = QtWidgets.QLineEdit(self.AddTaskPage)
        self.txtTitle.setGeometry(QtCore.QRect(39, 100, 420, 30))
        self.txtTitle.setFont(appFonts.getLineEditFont())
        self.txtTitle.setStyleSheet("QLineEdit{\n"
                                    "border: none;\n"
                                    "background-color: #E7E7E7;\n"
                                    "border-radius: 13px;\n"
                                    "text-align: center;\n"
                                    "}")
        self.txtTitle.setInputMethodHints(QtCore.Qt.ImhNone)
        self.txtTitle.setPlaceholderText("")
        self.txtTitle.setObjectName("txtTitle")
        self.lblTitle = QtWidgets.QLabel(self.AddTaskPage)
        self.lblTitle.setGeometry(QtCore.QRect(40, 60, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lblTitle.setFont(font)
        self.lblTitle.setStyleSheet("color: rgb(63, 61, 86);")
        self.lblTitle.setObjectName("lblTitle")
        self.btnTaskListener = QtWidgets.QPushButton(self.AddTaskPage)
        self.btnTaskListener.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnTaskListener.setGeometry(QtCore.QRect(210, 450, 80, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnTaskListener.sizePolicy().hasHeightForWidth())
        self.btnTaskListener.setSizePolicy(sizePolicy)
        self.btnTaskListener.setMaximumSize(QtCore.QSize(100, 100))
        self.btnTaskListener.setStyleSheet("QPushButton{\n"
                                           "background-color: rgb(62, 60, 84);\n"
                                           "border: 1px solid white;\n"
                                           "border-radius: 40;\n"
                                           "}\n"
                                           "QPushButton:pressed{\n"
                                           "    background-color: rgb(103, 100, 138);\n"
                                           "}")
        self.btnTaskListener.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(".\\Icons/Icon awesome-play@2x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnTaskListener.setIcon(icon8)
        self.btnTaskListener.setIconSize(QtCore.QSize(32, 32))
        self.btnTaskListener.setAutoDefault(False)
        self.btnTaskListener.setDefault(False)
        self.btnTaskListener.setObjectName("btnTaskListener")
        self.lblDescription = QtWidgets.QLabel(self.AddTaskPage)
        self.lblDescription.setGeometry(QtCore.QRect(40, 170, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lblDescription.setFont(font)
        self.lblDescription.setStyleSheet("color: rgb(63, 61, 86);")
        self.lblDescription.setObjectName("lblDescription")
        self.txtDescription = QtWidgets.QLineEdit(self.AddTaskPage)
        self.txtDescription.setGeometry(QtCore.QRect(39, 220, 420, 30))
        self.txtDescription.setFont(appFonts.getLineEditFont())
        self.txtDescription.setStyleSheet("QLineEdit{\n"
                                          "border: none;\n"
                                          "background-color: #E7E7E7;\n"
                                          "border-radius: 13px;\n"
                                          "text-align: center;\n"
                                          "}")
        self.txtDescription.setInputMethodHints(QtCore.Qt.ImhNone)
        self.txtDescription.setPlaceholderText("")
        self.txtDescription.setText("")
        self.txtDescription.setObjectName("txtDescription")
        self.lblRecordTask = QtWidgets.QLabel(self.AddTaskPage)
        self.lblRecordTask.setGeometry(QtCore.QRect(40, 300, 420, 70))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setItalic(False)
        self.lblRecordTask.setFont(font)
        self.lblRecordTask.setTextFormat(QtCore.Qt.RichText)
        self.lblRecordTask.setObjectName("lblRecordTask")
        self.btnBackToTasks = QtWidgets.QPushButton(self.AddTaskPage)
        self.btnBackToTasks.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnBackToTasks.setGeometry(QtCore.QRect(10, 10, 41, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnBackToTasks.sizePolicy().hasHeightForWidth())
        self.btnBackToTasks.setSizePolicy(sizePolicy)
        self.btnBackToTasks.setMaximumSize(QtCore.QSize(100, 100))
        self.btnBackToTasks.setStyleSheet("QPushButton{\n"
                                          "background-color: rgb(255, 255, 255);\n"
                                          "border: 1px solid white;\n"
                                          "border-radius: 20;\n"
                                          "}\n"
                                          "")
        self.btnBackToTasks.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(".\\Icons/Icon awesome-arrow-left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnBackToTasks.setIcon(icon9)
        self.btnBackToTasks.setIconSize(QtCore.QSize(32, 32))
        self.btnBackToTasks.setObjectName("btnBackToTasks")
        self.lblStartStopRec = QtWidgets.QLabel(self.AddTaskPage)
        self.lblStartStopRec.setGeometry(QtCore.QRect(58, 570, 401, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lblStartStopRec.setFont(font)
        self.lblStartStopRec.setStyleSheet("QLabel{\n"
                                           "text-align: center;\n"
                                           "color: rgb(62, 60, 84);\n"
                                           "letter-spacing: 1px;\n"
                                           "}")
        self.lblStartStopRec.setTextFormat(QtCore.Qt.MarkdownText)
        self.lblStartStopRec.setObjectName("lblStartStopRec")
        self.layoutWidget = QtWidgets.QWidget(self.AddTaskPage)
        self.layoutWidget.setGeometry(QtCore.QRect(190, 380, 132, 23))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblTutorial = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTutorial.sizePolicy().hasHeightForWidth())
        self.lblTutorial.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.lblTutorial.setFont(font)
        self.lblTutorial.setTextFormat(QtCore.Qt.RichText)
        self.lblTutorial.setObjectName("lblTutorial")
        self.horizontalLayout.addWidget(self.lblTutorial)
        self.btnTutorial = QtWidgets.QPushButton(self.layoutWidget)
        self.btnTutorial.setFocusPolicy(QtCore.Qt.NoFocus)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnTutorial.sizePolicy().hasHeightForWidth())
        self.btnTutorial.setSizePolicy(sizePolicy)
        self.btnTutorial.setMinimumSize(QtCore.QSize(40, 19))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setItalic(True)
        self.btnTutorial.setFont(font)
        self.btnTutorial.setStyleSheet("QPushButton{\n"
                                       "align: center;\n"
                                       "rgb(63, 61, 86)\n"
                                       "}")
        self.btnTutorial.setObjectName("btnTutorial")
        self.horizontalLayout.addWidget(self.btnTutorial)
        self.stackPanel.addWidget(self.AddTaskPage)
        self.menu = QtWidgets.QFrame(self.mainFrame)
        self.menu.setGeometry(QtCore.QRect(0, 30, 509, 681))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu.sizePolicy().hasHeightForWidth())
        self.menu.setSizePolicy(sizePolicy)
        self.menu.setMinimumSize(QtCore.QSize(509, 663))
        self.menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu.setObjectName("menu")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.menu)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(-1, 0, 521, 231))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setGeometry(QtCore.QRect(-1, 0, 521, 231))
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnAccount = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnAccount.setFocusPolicy(QtCore.Qt.NoFocus)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAccount.sizePolicy().hasHeightForWidth())
        self.btnAccount.setSizePolicy(sizePolicy)
        self.btnAccount.setMinimumSize(QtCore.QSize(0, 60))
        self.btnAccount.setFont(appFonts.getMenuButtonFont())
        self.btnAccount.setStyleSheet("QPushButton{\n"
                                      "background-image: url(Icons/user icon.png);\n"
                                      "background-repeat: no-repeat;\n"
                                      "background-repeat: no-repeat;\n"
                                      "background-position: left center;\n"
                                      "background-origin: content;\n"
                                      "text-align: left center;\n"
                                      "padding: 0 0 0 20;\n"
                                      "color: rgb(63, 61, 86);\n"
                                      "background-color: rgb(255, 255, 255);\n"
                                      "border-bottom: 1px solid rgb(63, 61, 86);\n"
                                      "\n"
                                      "}")
        self.btnAccount.setObjectName("btnAccount")
        self.verticalLayout.addWidget(self.btnAccount)
        self.btnDocumentation = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDocumentation.sizePolicy().hasHeightForWidth())
        self.btnDocumentation.setSizePolicy(sizePolicy)
        self.btnDocumentation.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnDocumentation.setMinimumSize(QtCore.QSize(0, 60))
        self.btnDocumentation.setFont(appFonts.getMenuButtonFont())
        self.btnDocumentation.setStyleSheet("QPushButton{\n"
                                            "background-image: url(Icons/file icon.png);\n"
                                            "background-repeat: no-repeat;\n"
                                            "background-position: left center;\n"
                                            "background-origin: content;\n"
                                            "text-align: left center;\n"
                                            "padding: 0 0 0 20;\n"
                                            "color: rgb(63, 61, 86);\n"
                                            "background-color: rgb(255, 255, 255);\n"
                                            "border-bottom: 1px solid rgb(63, 61, 86);\n"
                                            "\n"
                                            "}")
        self.btnDocumentation.setObjectName("btnDocumentation")
        self.verticalLayout.addWidget(self.btnDocumentation)
        self.btnFAQ = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnFAQ.setFocusPolicy(QtCore.Qt.NoFocus)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnFAQ.sizePolicy().hasHeightForWidth())
        self.btnFAQ.setSizePolicy(sizePolicy)
        self.btnFAQ.setMinimumSize(QtCore.QSize(0, 60))
        self.btnFAQ.setFont(appFonts.getMenuButtonFont())
        self.btnFAQ.setStyleSheet("QPushButton{\n"
                                  "background-image: url(Icons/question icon.png);\n"
                                  "background-repeat: no-repeat;\n"
                                  "background-position: left center;\n"
                                  "background-origin: content;\n"
                                  "text-align: left center;\n"
                                  "padding: 0 0 0 20;\n"
                                  "color: rgb(63, 61, 86);\n"
                                  "background-color: rgb(255, 255, 255);\n"
                                  "border-bottom: 1px solid rgb(63, 61, 86);\n"
                                  "\n"
                                  "}")
        self.btnFAQ.setObjectName("btnFAQ")
        self.verticalLayout.addWidget(self.btnFAQ)
        self.btnLogout = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnLogout.setFocusPolicy(QtCore.Qt.NoFocus)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnLogout.sizePolicy().hasHeightForWidth())
        self.btnLogout.setSizePolicy(sizePolicy)
        self.btnLogout.setMinimumSize(QtCore.QSize(0, 60))
        self.btnLogout.setFont(appFonts.getMenuButtonFont())
        self.btnLogout.setStyleSheet("QPushButton{\n"
                                     "background-image: url(Icons/logout icon.png);\n"
                                     "background-repeat: no-repeat;\n"
                                     "background-position: left center;\n"
                                            "background-origin: content;\n"
                                            "text-align: left center;\n"
                                            "padding: 0 0 0 20;\n"
                                     "color: rgb(63, 61, 86);\n"
                                     "background-color: rgb(255, 255, 255);\n"
                                     "border-bottom: 1px solid rgb(63, 61, 86);\n"
                                     "}")
        self.btnLogout.setObjectName("btnLogout")
        self.verticalLayout.addWidget(self.btnLogout)
        self.menu.lower()
        self.title_bar.raise_()
        self.stackPanel.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackPanel.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblLogin.setText(_translate("MainWindow", "Log in"))
        self.lblorviaEmail_login.setText(_translate("MainWindow", "or via E-mail"))
        self.lblEmail.setText(_translate("MainWindow", "Email"))
        self.txtEmail_login.setPlaceholderText(_translate("MainWindow", "email@example.com"))
        self.lblPassword.setText(_translate("MainWindow", "Password"))
        self.txtPassword_login.setPlaceholderText(_translate("MainWindow", "Password"))
        self.chkRememberme.setText(_translate("MainWindow", "Remember Me"))
        self.btnForgotpwd.setText(_translate("MainWindow", "Forgot Password?"))
        self.btnLogin.setText(_translate("MainWindow", "Log in"))
        self.lblDontHaveAnAccount.setText(_translate("MainWindow", "Don\'t have an account?"))
        self.btnSignupPage.setText(_translate("MainWindow", "Sign up"))
        self.lblSignup.setText(_translate("MainWindow", "Sign up"))
        self.lblorviaEmail.setText(_translate("MainWindow", "or via E-mail"))
        self.lblEmail_signup.setText(_translate("MainWindow", "Email"))
        self.txtEmail_signup.setPlaceholderText(_translate("MainWindow", "email@example.com"))
        self.lblPassword_signup.setText(_translate("MainWindow", "Password"))
        self.txtPassword_signup.setPlaceholderText(_translate("MainWindow", "Password"))
        self.lblConfirmPassword.setText(_translate("MainWindow", "Confirm Password"))
        self.txtConfirmPassword_signup.setPlaceholderText(_translate("MainWindow", "Confirm Password"))
        self.btnSignup.setText(_translate("MainWindow", "Sign Up"))
        self.lblHaveanAccount.setText(_translate("MainWindow", "Already have an account?"))
        self.btnLoginPage.setText(_translate("MainWindow", "Login"))
        self.lblTranscript.setText(_translate("MainWindow", "Transcript"))
        self.lblLiveTranscript.setText(_translate("MainWindow", "boilerplate code"))
        self.lblTitle.setText(_translate("MainWindow", "Title"))
        self.lblDescription.setText(_translate("MainWindow", "Description"))
        self.txtTitle.setPlaceholderText(_translate("MainWindow", ""))
        self.txtDescription.setPlaceholderText(_translate("MainWindow", ""))
        self.lblRecordTask.setText(_translate("MainWindow",
                                              "<html><head/><body><p align=\"center\">Once you START recording, "
                                              "Do the desired task from </p><p align=\"center\">start to finish one "
                                              "time and than END recording. </p><p "
                                              "align=\"center\"><br/></p></body></html>"))
        self.lblStartStopRec.setText(_translate("MainWindow", "Click here to START recording task"))
        self.lblTutorial.setText(_translate("MainWindow", "<html><head/><body><p>See Tutorial </p></body></html>"))
        self.btnTutorial.setText(_translate("MainWindow", "Here"))
        self.btnAccount.setText(_translate("MainWindow", "            Account"))
        self.btnDocumentation.setText(_translate("MainWindow", "            Documentation"))
        self.btnFAQ.setText(_translate("MainWindow", "            FAQ"))
        self.btnLogout.setText(_translate("MainWindow", "            Logout"))
