Mail:
- timeSleep:
    sleep: 0.9
- hotKeyPress: Key.cmd
- hotKeyRelease: Key.cmd
- timeSleep:
    sleep: 0.9
- m
- a
- i
- l
- timeSleep:
    sleep: 0.9
- hotKeyPress: Key.enter
- hotKeyRelease: Key.enter
- timeSleep:
    sleep: 0.9
Demo2:
- timeSleep:
    sleep: 2.7592005729675293
- moveTo:
    x: 717
    y: 1060
- leftClick:
    x: 717
    y: 1060
- timeSleep:
    sleep: 2.6309685707092285
- moveTo:
    x: 1253
    y: 112
- leftClick:
    x: 1253
    y: 112
- timeSleep:
    sleep: 0.9918131828308105
- moveTo:
    x: 971
    y: 690
- leftClick:
    x: 971
    y: 690
