Test1:
- timeSleep:
    sleep: 2.823289632797241
- moveTo:
    x: 1432
    y: 214
- leftClick:
    x: 1432
    y: 214
- timeSleep:
    sleep: 2.103083372116089
- moveTo:
    x: 1486
    y: 73
- leftClick:
    x: 1486
    y: 73
- timeSleep:
    sleep: 1
- hotKeyPress: Key.ctrl_l
- "\x06"
- hotKeyRelease: Key.ctrl_l
- timeSleep:
    sleep: 1
- y
- a
- m
- l
- l
