Demo:
- timeSleep:
    sleep: 0.9
- hotKeyPress: Key.cmd
- hotKeyRelease: Key.cmd
- timeSleep:
    sleep: 0.9
- m
- a
- timeSleep:
    sleep: 0.9
- hotKeyPress: Key.enter
- hotKeyRelease: Key.enter
- timeSleep:
    sleep: 0.9
- timeSleep:
    sleep: 5.197579860687256
- moveTo:
    x: 1590
    y: 110
- leftClick:
    x: 1590
    y: 110
- timeSleep:
    sleep: 1.0172317028045654
- moveTo:
    x: 1599
    y: 720
- leftClick:
    x: 1599
    y: 720
